export interface Signal {
  id: string;
  tokenAddress: string;
  tokenSymbol: string;
  tokenName: string;
  price: number;
  priceChange24h: number;
  volume24h: number;
  marketCap: number;
  liquidity: number;
  confidence: number; // 0-100 score
  sentiment: 'bullish' | 'bearish' | 'neutral';
  source: 'dexscreener' | 'birdeye' | 'pumpfun' | 'onchain' | 'autonomous_agent';
  timestamp: Date;
  metadata?: {
    topHolders?: string[];
    devWallet?: string;
    snipers?: string[];
    insiders?: string[];
    analysis?: string;
    holderCount?: number;
    decimals?: number;
    pairAddress?: string;
    txns24h?: { buys: number; sells: number };
    isKing?: boolean;
    createdAt?: string;
    autoGenerated?: boolean;
    userId?: string;
    socials?: {
      twitter?: string;
      telegram?: string;
      website?: string;
    };
  };
  status: 'active' | 'expired' | 'triggered';
}

export interface SignalFilter {
  tokenAddress?: string;
  minConfidence?: number;
  minLiquidity?: number;
  minVolume24h?: number;
  sentiment?: Signal['sentiment'][];
  source?: Signal['source'][];
}
